import { mkdir, writeFile } from 'node:fs/promises';
import * as path from 'node:path';

import type { ArtifactRef, StageId } from '../types/index.js';
import type { Stage } from './spec-types.js';
import type {
  UxAcceptanceCheck,
  UxAcceptanceChecklist,
  UxAcceptanceStageInput,
  UxAcceptanceStageOutput,
  UxAcceptanceStageOptions,
  UxAcceptanceTarget,
  UxSopDocument,
  UxSopStep,
} from './ux-acceptance-types.js';

export class UxAcceptanceStage implements Stage<UxAcceptanceStageInput, UxAcceptanceStageOutput> {
  readonly stageId: StageId = 'ux-acceptance-authoring' as const;
  private readonly now: () => string;

  constructor(private readonly options: UxAcceptanceStageOptions) {
    this.now = options.now ?? (() => new Date().toISOString());
  }

  async execute(input: UxAcceptanceStageInput): Promise<UxAcceptanceStageOutput> {
    const checks: UxAcceptanceCheck[] = [];

    for (const target of input.targets) {
      const check = await this.runCheck(target);
      checks.push(check);
    }

    const failedChecks = checks.filter((c) => c.status === 'fail');
    const allPassed = failedChecks.length === 0;

    const checklist: UxAcceptanceChecklist = { checks, allPassed, failedChecks };

    const timestamp = this.now();
    const artifact = await this.writeArtifact(input, checklist, timestamp);

    const passed = checks.filter((c) => c.status === 'pass').length;
    const skipped = checks.filter((c) => c.status === 'skip').length;

    return {
      checklist,
      metadata: {
        totalChecks: checks.length,
        passed,
        failed: failedChecks.length,
        skipped,
        authoredAt: timestamp,
        authorRole: 'ux',
      },
      artifact,
      // AC-4.24u2: Generate reusable SOP document from acceptance checks
      ...await this.generateSop(input, checks, timestamp),
    };
  }

  private async runCheck(target: UxAcceptanceTarget): Promise<UxAcceptanceCheck> {
    if (!this.options.adapter.runUxCheck) {
      return {
        id: target.id,
        description: target.description,
        category: target.category,
        status: 'skip',
        detail: 'No UX acceptance adapter provided',
      };
    }

    const response = await this.options.adapter.runUxCheck({ target });
    return {
      id: target.id,
      description: target.description,
      category: target.category,
      status: response.status,
      detail: response.detail,
    };
  }

  /**
   * AC-4.24u2: Generate a reusable SOP document from the acceptance checks.
   * The SOP includes navigation paths, interaction steps, expected results,
   * and screenshot placeholders. Persisted to the project docs/ directory.
   */
  private async generateSop(
    input: UxAcceptanceStageInput,
    checks: UxAcceptanceCheck[],
    timestamp: string,
  ): Promise<{ sopDocument: UxSopDocument; sopArtifact: ArtifactRef }> {
    const steps: UxSopStep[] = checks.map((check, idx) => ({
      step: idx + 1,
      page: check.category,
      action: check.description,
      expectedResult: check.status === 'pass'
        ? (check.detail ?? 'Verification passed')
        : check.status === 'fail'
          ? `FAILED: ${check.detail ?? 'Check did not pass'}`
          : 'Skipped',
      screenshotPath: `screenshots/${input.taskId}-step-${idx + 1}.png`,
    }));

    const sopDocument: UxSopDocument = {
      taskId: input.taskId,
      generatedAt: timestamp,
      steps,
    };

    // Persist SOP as markdown in docs/
    const basePath = input.artifactBasePath
      ?? path.join(process.cwd(), 'artifacts', 'ux-acceptance');
    await mkdir(basePath, { recursive: true });

    const sopPath = path.join(basePath, `${input.taskId}-ux-sop.md`);
    const markdown = this.renderSopMarkdown(sopDocument);
    await writeFile(sopPath, markdown, 'utf8');

    const sopArtifact: ArtifactRef = {
      id: `${input.taskId}:ux-sop`,
      type: 'ux-sop',
      path: sopPath,
      createdAt: timestamp,
      metadata: { stepCount: steps.length },
    };

    return { sopDocument, sopArtifact };
  }

  /**
   * AC-4.24u2: Render SOP document as markdown.
   */
  private renderSopMarkdown(sop: UxSopDocument): string {
    const lines: string[] = [
      `# UX Acceptance SOP — ${sop.taskId}`,
      '',
      `Generated: ${sop.generatedAt}`,
      '',
      '## Verification Steps',
      '',
      '| Step | Page/Category | Action | Expected Result | Screenshot |',
      '|------|---------------|--------|-----------------|------------|',
    ];

    for (const step of sop.steps) {
      lines.push(
        `| ${step.step} | ${step.page} | ${step.action} | ${step.expectedResult} | ${step.screenshotPath ?? '-'} |`,
      );
    }

    lines.push('', '---', '', '_Auto-generated by SEVO UX Acceptance Stage. Edit and reuse for subsequent iterations._', '');
    return lines.join('\n');
  }

  private async writeArtifact(
    input: UxAcceptanceStageInput,
    checklist: UxAcceptanceChecklist,
    timestamp: string,
  ): Promise<ArtifactRef> {
    const basePath = input.artifactBasePath
      ?? path.join(process.cwd(), 'artifacts', 'ux-acceptance');
    await mkdir(basePath, { recursive: true });

    const filePath = path.join(basePath, `${input.taskId}-ux-acceptance.json`);
    await writeFile(filePath, JSON.stringify({ ...checklist, authoredAt: timestamp }, null, 2), 'utf8');

    return {
      id: `${input.taskId}:ux-acceptance`,
      type: 'ux-acceptance-checklist',
      path: filePath,
      createdAt: timestamp,
      metadata: { checkCount: checklist.checks.length, allPassed: checklist.allPassed },
    };
  }
}