/**
 * Stage 6: implement
 *
 * Reads spec FRs and contracts, then writes scaffolding source files
 * under src/<fr-slug>/index.ts that satisfy the contract shapes.
 *
 * If LLM is available it asks for a real implementation; otherwise it
 * emits typed stubs that compile and let downstream stages exercise the
 * real file system. Either way every FR gets a real source file.
 */

import * as path from 'node:path';

import type { StageHandler, StageHandlerResult } from './types.js';
import {
  ensureDir,
  makeArtifact,
  nowIso,
  parseLlmJson,
  readJsonIfExists,
  slugify,
  writeFileEnsure,
} from './utils.js';

interface SpecJson {
  functionalRequirements?: Array<{
    title?: string;
    description?: string;
    acceptanceCriteria?: string[];
  }>;
}

interface LlmImplPayload {
  files?: Array<{ relPath: string; content: string }>;
}

const IMPL_SYSTEM_PROMPT = [
  'You are a TypeScript engineer scaffolding a SEVO project module.',
  'Output STRICT JSON, no markdown fences:',
  '{ "files": [ { "relPath": "src/<fr-slug>/index.ts", "content": "..." } ] }',
  'Use ES modules with .js extensions in import paths.',
  'Each FR gets one file at src/<fr-slug>/index.ts that exports a default async',
  'function returning { success: boolean, artifacts: string[] }. Keep it short.',
].join('\n');

function renderStubModule(args: {
  frId: string;
  title: string;
  description: string;
  acs: string[];
  generatedAt: string;
}): string {
  const fnName = slugify(args.title)
    .replace(/-([a-z])/g, (_, c: string) => c.toUpperCase())
    .replace(/^[^a-zA-Z]+/, '');
  const safeName = fnName || 'execute';
  const lines: string[] = [];
  lines.push('/**');
  lines.push(` * Auto-generated by SEVO implement stage.`);
  lines.push(` * Generated: ${args.generatedAt}`);
  lines.push(` * FR: ${args.frId} ${args.title}`);
  lines.push(' */');
  lines.push('');
  lines.push(`export interface ${args.frId.replace(/-/g, '')}Result {`);
  lines.push('  success: boolean;');
  lines.push('  artifacts: string[];');
  lines.push('}');
  lines.push('');
  lines.push(`/** Stub implementation for ${args.frId}. Fill in real logic during review-fix-loop. */`);
  lines.push(
    `export async function ${safeName}(): Promise<${args.frId.replace(/-/g, '')}Result> {`,
  );
  lines.push('  return { success: true, artifacts: [] };');
  lines.push('}');
  lines.push('');
  lines.push(`export default ${safeName};`);
  lines.push('');
  return lines.join('\n');
}

export const implementHandler: StageHandler = async (ctx): Promise<StageHandlerResult> => {
  const generatedAt = nowIso(ctx.now);
  const docsDir = path.join(ctx.projectRoot, 'docs');
  const spec = readJsonIfExists<SpecJson>(path.join(docsDir, 'product-requirements.json'));
  const frs = spec?.functionalRequirements ?? [];

  if (frs.length === 0) {
    const manifestPath = path.join(ctx.projectRoot, 'src', 'implement-manifest.json');
    writeFileEnsure(
      manifestPath,
      JSON.stringify(
        { pipelineId: ctx.pipelineId, generatedAt, frCount: 0, files: [], usedLlm: false },
        null,
        2,
      ) + '\n',
    );
    return {
      stageId: 'implement',
      verdict: 'block',
      artifacts: [
        makeArtifact({
          id: `${ctx.pipelineId}:implement-manifest`,
          type: 'implement-manifest',
          filePath: manifestPath,
          createdAt: generatedAt,
        }),
      ],
      summary: 'No FR to implement.',
      issues: ['No FR found in spec'],
      metadata: { frCount: 0, usedLlm: false },
    };
  }

  let llmFiles: LlmImplPayload | null = null;
  if (ctx.llm) {
    try {
      const userPrompt = JSON.stringify(
        {
          projectSlug: ctx.projectSlug,
          functionalRequirements: frs.map((fr, i) => ({
            id: `FR-${String(i + 1).padStart(2, '0')}`,
            title: fr.title?.trim() ?? '',
            description: fr.description?.trim() ?? '',
            acceptanceCriteria: (fr.acceptanceCriteria ?? []).filter((a) => a?.trim()),
          })),
        },
        null,
        2,
      );
      const raw = await ctx.llm.chat([
        { role: 'system', content: IMPL_SYSTEM_PROMPT },
        { role: 'user', content: userPrompt },
      ]);
      llmFiles = parseLlmJson<LlmImplPayload>(raw);
    } catch {
      llmFiles = null;
    }
  }

  const written: Array<{ frId: string; relPath: string; filePath: string; source: 'llm' | 'stub' }> = [];

  if (llmFiles && Array.isArray(llmFiles.files) && llmFiles.files.length > 0) {
    for (const f of llmFiles.files) {
      if (!f.relPath || typeof f.content !== 'string') continue;
      const safeRel = f.relPath.replace(/^[\\/]+/, '');
      const filePath = path.join(ctx.projectRoot, safeRel);
      writeFileEnsure(filePath, f.content);
      const frMatch = safeRel.match(/(FR-\d+|fr-\d+)/i);
      const frId = frMatch?.[1]?.toUpperCase().replace(/^FR-0?/, 'FR-') ?? '';
      written.push({ frId, relPath: safeRel, filePath, source: 'llm' });
    }
  }

  // Ensure every FR has at least one file (LLM may miss some).
  const frIdsCovered = new Set(written.map((w) => w.frId).filter(Boolean));
  for (let i = 0; i < frs.length; i++) {
    const frId = `FR-${String(i + 1).padStart(2, '0')}`;
    if (frIdsCovered.has(frId)) continue;
    const fr = frs[i];
    if (!fr) continue;
    const title = fr.title?.trim() || `Requirement ${i + 1}`;
    const acs = (fr.acceptanceCriteria ?? []).filter((a) => a?.trim());
    const relPath = path.join('src', `${frId.toLowerCase()}-${slugify(title)}`, 'index.ts');
    const filePath = path.join(ctx.projectRoot, relPath);
    writeFileEnsure(
      filePath,
      renderStubModule({
        frId,
        title,
        description: fr.description?.trim() ?? '',
        acs,
        generatedAt,
      }),
    );
    written.push({ frId, relPath, filePath, source: 'stub' });
  }

  const manifestPath = path.join(ctx.projectRoot, 'src', 'implement-manifest.json');
  const usedLlm = written.some((w) => w.source === 'llm');
  writeFileEnsure(
    manifestPath,
    JSON.stringify(
      {
        pipelineId: ctx.pipelineId,
        projectSlug: ctx.projectSlug,
        generatedAt,
        frCount: frs.length,
        usedLlm,
        files: written.map((w) => ({
          frId: w.frId,
          relPath: w.relPath,
          source: w.source,
        })),
      },
      null,
      2,
    ) + '\n',
  );

  return {
    stageId: 'implement',
    verdict: 'pass',
    artifacts: [
      makeArtifact({
        id: `${ctx.pipelineId}:implement-manifest`,
        type: 'implement-manifest',
        filePath: manifestPath,
        createdAt: generatedAt,
        metadata: { frCount: frs.length, usedLlm, fileCount: written.length },
      }),
      ...written.map((w) =>
        makeArtifact({
          id: `${ctx.pipelineId}:impl:${w.frId || w.relPath}`,
          type: 'implement-source',
          filePath: w.filePath,
          createdAt: generatedAt,
          metadata: { frId: w.frId, source: w.source },
        }),
      ),
    ],
    summary: `Wrote ${written.length} source file(s) covering ${frs.length} FR (llm=${usedLlm}).`,
    issues: [],
    metadata: { frCount: frs.length, usedLlm, fileCount: written.length, manifestPath },
  };
};
