/**
 * Stage 3: test-case-authoring
 *
 * Reads docs/product-requirements.json (or .md as fallback) and emits
 * src/tests/<fr-id>.test.ts files — one test per FR with one expectation
 * per AC, plus a summary src/tests/_test-plan.json.
 *
 * Real output: actual TypeScript test files that vitest can pick up.
 */

import * as fs from 'node:fs';
import * as path from 'node:path';

import type { StageHandler, StageHandlerResult } from './types.js';
import {
  ensureDir,
  makeArtifact,
  nowIso,
  readJsonIfExists,
  readTextIfExists,
  slugify,
  writeFileEnsure,
} from './utils.js';

interface SpecFR {
  id: string;
  title: string;
  description: string;
  acceptanceCriteria: string[];
}

interface SpecJson {
  functionalRequirements?: Array<{
    title?: string;
    description?: string;
    acceptanceCriteria?: string[];
  }>;
}

function loadFRs(projectRoot: string): SpecFR[] {
  const docsDir = path.join(projectRoot, 'docs');
  const json = readJsonIfExists<SpecJson>(path.join(docsDir, 'product-requirements.json'));
  if (json && Array.isArray(json.functionalRequirements)) {
    return json.functionalRequirements.map((fr, idx) => ({
      id: `FR-${String(idx + 1).padStart(2, '0')}`,
      title: fr.title?.trim() || `Requirement ${idx + 1}`,
      description: fr.description?.trim() || '',
      acceptanceCriteria: (fr.acceptanceCriteria ?? []).filter((a) => a?.trim()),
    }));
  }

  const md = readTextIfExists(path.join(docsDir, 'product-requirements.md'));
  if (!md) return [];

  const frs: SpecFR[] = [];
  const lines = md.split('\n');
  let cur: SpecFR | null = null;
  for (const line of lines) {
    const frMatch = line.match(/^###\s+(FR-\d+)\s+(.+)$/);
    if (frMatch && frMatch[1] && frMatch[2]) {
      if (cur) frs.push(cur);
      cur = { id: frMatch[1], title: frMatch[2].trim(), description: '', acceptanceCriteria: [] };
      continue;
    }
    const acMatch = line.match(/^[-*]\s+AC-\d+\.\d+\s+(.+)$/);
    if (acMatch && acMatch[1] && cur) {
      cur.acceptanceCriteria.push(acMatch[1].trim());
    }
  }
  if (cur) frs.push(cur);
  return frs;
}

function escapeForTemplate(s: string): string {
  return s.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${');
}

function renderTestFile(fr: SpecFR, generatedAt: string): string {
  const acs = fr.acceptanceCriteria.length > 0 ? fr.acceptanceCriteria : ['(待补充)'];
  const lines: string[] = [];
  lines.push('/**');
  lines.push(` * Auto-generated by SEVO test-case-authoring stage.`);
  lines.push(` * Generated: ${generatedAt}`);
  lines.push(` * FR: ${fr.id} ${fr.title}`);
  lines.push(' */');
  lines.push("import { describe, it, expect } from 'vitest';");
  lines.push('');
  lines.push(`describe('${fr.id} ${escapeForTemplate(fr.title)}', () => {`);
  acs.forEach((ac, idx) => {
    const acId = `AC-${fr.id.replace(/^FR-0?/, '')}.${idx + 1}`;
    lines.push(`  it('${acId} ${escapeForTemplate(ac).replace(/'/g, "\\'")}', () => {`);
    lines.push(`    // TODO: implement assertion for: ${escapeForTemplate(ac)}`);
    lines.push(`    expect(true).toBe(true);`);
    lines.push('  });');
  });
  lines.push('});');
  lines.push('');
  return lines.join('\n');
}

export const testCaseAuthoringHandler: StageHandler = async (ctx): Promise<StageHandlerResult> => {
  const generatedAt = nowIso(ctx.now);
  const frs = loadFRs(ctx.projectRoot);

  const testsDir = path.join(ctx.projectRoot, 'src', 'tests');
  ensureDir(testsDir);

  if (frs.length === 0) {
    const planPath = path.join(testsDir, '_test-plan.json');
    writeFileEnsure(
      planPath,
      JSON.stringify(
        { pipelineId: ctx.pipelineId, generatedAt, frCount: 0, testCount: 0, files: [] },
        null,
        2,
      ) + '\n',
    );
    return {
      stageId: 'test-case-authoring',
      verdict: 'block',
      artifacts: [
        makeArtifact({
          id: `${ctx.pipelineId}:test-plan`,
          type: 'test-plan',
          filePath: planPath,
          createdAt: generatedAt,
        }),
      ],
      summary: 'No FR found in spec — cannot author tests.',
      issues: ['No FR found in spec'],
      metadata: { frCount: 0, testCount: 0 },
    };
  }

  const written: Array<{ frId: string; filePath: string; testCount: number }> = [];
  for (const fr of frs) {
    const fileName = `${fr.id.toLowerCase()}-${slugify(fr.title)}.test.ts`;
    const filePath = path.join(testsDir, fileName);
    const testFile = renderTestFile(fr, generatedAt);
    writeFileEnsure(filePath, testFile);
    written.push({
      frId: fr.id,
      filePath,
      testCount: Math.max(fr.acceptanceCriteria.length, 1),
    });
  }

  const totalTests = written.reduce((sum, w) => sum + w.testCount, 0);
  const planPath = path.join(testsDir, '_test-plan.json');
  const plan = {
    pipelineId: ctx.pipelineId,
    projectSlug: ctx.projectSlug,
    generatedAt,
    frCount: frs.length,
    testCount: totalTests,
    files: written.map((w) => ({
      frId: w.frId,
      relPath: path.relative(ctx.projectRoot, w.filePath),
      testCount: w.testCount,
    })),
  };
  writeFileEnsure(planPath, JSON.stringify(plan, null, 2) + '\n');

  // Also verify each generated file is on disk (defensive — catches FS races).
  const verifiedAll = written.every((w) => fs.existsSync(w.filePath));

  return {
    stageId: 'test-case-authoring',
    verdict: verifiedAll ? 'pass' : 'fail',
    artifacts: [
      makeArtifact({
        id: `${ctx.pipelineId}:test-plan`,
        type: 'test-plan',
        filePath: planPath,
        createdAt: generatedAt,
        metadata: { frCount: frs.length, testCount: totalTests },
      }),
      ...written.map((w) =>
        makeArtifact({
          id: `${ctx.pipelineId}:test:${w.frId}`,
          type: 'test-file',
          filePath: w.filePath,
          createdAt: generatedAt,
          metadata: { frId: w.frId, testCount: w.testCount },
        }),
      ),
    ],
    summary: `Authored ${written.length} test file(s), ${totalTests} test case(s) covering ${frs.length} FR.`,
    issues: verifiedAll ? [] : ['Some test files failed to verify on disk'],
    metadata: { frCount: frs.length, testCount: totalTests, planPath },
  };
};
